### ISSUE TITLE
Data context as View's id not working properly

### ISSUE THREAD

**Issue by Wenape** [gadicc/meteor-famous-views#100]
Using famousEach, I set the id of each View to the _id of it's corresponding element.

`{{#famousEach tracks}} {{>View template="Track" id=this._id size='[undefined, 100]' opacity=0}} {{/famousEach}}`

For 5 random elements, the output is:
 `debug:  [famous-views] New View (#5), content from "Track" (parent: famousEach, template: Template.Player)`
 `debug:  [famous-views] New View (#JbtQ5TQpiQmykAEAk), content from "Track" (parent: famousEach, template: Template.Player)`
 `debug:  [famous-views] New View (#6), content from "Track" (parent: famousEach, template: Template.Player)`
  `debug:  [famous-views] New View (#9), content from "Track" (parent: famousEach, template: Template.Player)`
  `debug:  [famous-views] New View (#d3PTCwLjCFRWZ82P4), content from "Track" (parent: famousEach, template: Template.Player)`

When using the 'this._id' property, some views get the correct id and others just a random 0-9 number.
This problem occurs with any other property as well, like 'this.name', 'this.duration', 'this.votes' or any other.

I wonder if some of these properties contain restricted characters which makes famous-views fallback to a default id (as if no id was set in the first place)

**Comment by ddresch** [comment]
This is more a question than an issue, so I'm wondering if this approach is valid? How you would do it?

I got this setup:

```
<template name="startpage">
  {{#GridLayout size="[undefined,undefined]" dimensions="[1,2]" gutterSize="[10,10]"}}
    {{#famousEach buttons}}
      {{>ContainerSurface template='gridButton' modifier="StateModifier" overflow="hidden"}}
    {{/famousEach}}
  {{/GridLayout}}
</template>
```

```
<template name="gridButton">
  {{#Surface size="[undefined,undefined]" class=colorScheme}}{{/Surface}} 
  {{#Surface size="[undefined,50]" class='btn-grid-label' origin="[0.5,0.5]" align="[0.5,0.5]" translate='[0,0,1]'}}
    {{title}}
  {{/Surface}}
</template>
```

```
Template.startpage.helpers({
  buttons: function () {
    return [
      {title: 'Button 1', path: 'select-level', color: 'color1'},
      {title: 'Button 2', path: 'stepsInfo', color: 'color2'}
    ];
  }
});
```

```
Template.gridButton.famousEvents({
  'click': function(e, fview){
    tplData = Blaze.getData(fview.blazeView);    
    Router.go(tplData.path);
  }
});
```

Before the current update of `famous-views ` I could do it that way to get the context of each gridButton template:

    tplData = Blaze.getData(fview.children[0].surfaceBlazeView);

Now the property surfaceBlazeView isn't available anymore and getData returns:

   tplData = Blaze.getData(fview.blazeView);

```
Object
  class: "btn btn-block scheme1 color2"
  modifier: "StateModifier"
  size: Array[2]
  view: "Surface"
```

So any hints welcome, thx :)

**Comment by ddresch** [comment]
Found a solution to my specific problem. Needed to add `data=this` to the Surface, I'm not sure if this is a version specific problem or not.

Have a look here if you like: 

https://fview-lab.meteor.com/pads/53sHoTJ9JHDFbx5Qt/1
