### ISSUE TITLE
Using the HeaderFooterLayout, the Footer slides up with keyboard/number

### ISSUE THREAD

**Issue by philcruz** [gadicc/meteor-famous-views#147]
Using the HeaderFooterLayout, if the content area has a text field for input, when you type into the field on a mobile browser (i.e. Chrome on Android) the Footer slides up with the keyboard (and can obscure the field you are typing into). I was expecting the Footer to stay at the bottom.

![2014-11-19 22 40 31](https://cloud.githubusercontent.com/assets/281846/5115951/6fd9c00a-6ffa-11e4-9606-fec26eff2d03.png)

![2014-11-19 22 40 41](https://cloud.githubusercontent.com/assets/281846/5115956/734860c0-6ffa-11e4-9de7-a049c4140cdf.png)

I thought this might be an issue with Famous so I opened an issue on that project. (https://github.com/Famous/famous/issues/375)

Turns out if I set the size of the context like

mainContext.add(new Modifier({size: [window.innerWidth, window.innerHeight]})).add(layout);

that would resolve the issue. Not sure how to achieve the same thing using famous-views. Check out this meteorpad which demonstrates the problem. 

http://meteorpad.com/pad/gTuHyu3QpA4hRdMSL

Thanks,
Phil

**Comment by feidens** [comment]
@gadicc How to accommodate resizes?

**Comment by PEM--** [comment]
Personally, I rely on [reactive-window](https://github.com/gadicc/meteor-reactive-window) for all viewport resizing. If you need more fine grained events, you can also listen for DOM native events like `resize` [as proposed by famo.us](http://famo.us/guides/events).

**Comment by gadicc** [comment]
For reference:
https://github.com/FamousMobileApps/playbook_famous_phonegap/blob/master/views/keyboard.md
