### ISSUE TITLE
deferred destroy not removing views from sequence

### ISSUE THREAD

**Issue by mcbain** [gadicc/meteor-famous-views#153]
When removing one middle column [-] in the  #Animate example there is always a small white gap between the remaining columns. 

http://meteorpad.com/pad/rXrmAYnMtuP7rnFeD/#Animate

Debugging into the used SequentialLayout shows that there are still three views in the ViewSequence, after invoking View.destroy() after transition end.

![destroybug](https://cloud.githubusercontent.com/assets/342739/5153782/c5646336-7239-11e4-8788-24d1468c6818.png)

The code path from meteorFamousView.js with all the TODO is taken in my example.

     // If we're part of a sequence, now is the time to remove ourselves
      if (fview.parent.sequence) {
        if (fview.sequence) {
           // TODO, we're a child sequence, remove the child (TODO in sequencer.js)
          // log.debug("child sequence");
        } else {
          famous.core.Engine.defer(function() {
            fview.parent.sequence.remove(fview);  // less flicker in a defer
          });
        }
      }

**Comment by gadicc** [comment]
Flawed logic on my part :(  Removing child sequences isn't so urgent/important, but the *if* condition should have *always* removed the child until the other code is written.  Fixed, made that clearer, and will be in 0.1.31.
