### ISSUE TITLE
Events page on Mobile Chrome is slow

### ISSUE THREAD

**Issue by LiShine** [gadicc/meteor-famous-views#168]
Chrome 39.0.2171.59
Android 5.0
https://famous-views.meteor.com/examples/events
Gets stuck or slowed down
While in Opera, it behaves fine

**Comment by gadicc** [comment]
Btw, can you give some more specifics about which parts of the page break?
In Android 4.4.4 with Chrome 40.0.2214.89 the page works fine.
Not that the animations themselves are that great :)  But no slowdown or breakage.
For the bottom ball demo, I did have to click off the ball and then on it again to simulate `onmouseover`.
