### ISSUE TITLE
Performance Issues with way too many reactive blaze templates

### ISSUE THREAD

**Issue by monbro** [gadicc/meteor-famous-views#187]
I am building a simple web app with has a animated sidebar and a content area with the focus on mobile first.

I experienced the following as I was using a table plugin in my content area (which is embedded in a simple surface and this in a scrollview) with about 80 rows with 5 columns (was using ~200 reactive blaze templates in one view maybe?). The table plugin I was trying is https://github.com/ecohealthalliance/reactive-table - previously I was using http://datatables.net/ which is fast but works with jquery a lot and in addition it is somehow not rendered within a famous surface.

The Problem: The famous animations are going to be far to slow. First I thought it is an issue with famous itself or my animations or my css. But actually when removing the reactive table plugin it was much more fast again and fluent.

So maybe I did not see a notice on that, but maybe it would make sense to give add something to the documentation (especially for too optimistic people like me) that you should be careful with what you put in the surfaces and that the performance is limited.

Hopefully my issue makes sense to you somehow.

**Comment by gadicc** [comment]
Try `gadicohen:famous-views@0.1.33-flushPreview` and let me know if you notice a big difference (you should!) and if nothing breaks.

**Comment by gadicc** [comment]
And now `gadicohen:famous-views@0.1.33-flushPreview.1`.  Closing this issue and tracking in https://github.com/gadicc/meteor-famous-views/issues/215.

**Comment by gadicc** [comment]
However, @monbro, if you still by chance have your original code as your disposal I'd love to know how this release affects the problem you described above.
