### ISSUE TITLE
Timbre menu with HeaderFooterLayout

### ISSUE THREAD

**Issue by philcruz** [gadicc/meteor-famous-views#190]
I have an app using a HeaderFooterLayout with a scroll view so you can page through the content section. (Like http://meteorpad.com/pad/gTuHyu3QpA4hRdMSL).

I want to now add a menu like the timbre menu. So I tried something like

    <template name="home">
    {{#ContainerSurface size="[undefined,undefined]" overflow="hidden" class="timbre-cs"}}
     {{> timbre_menu}}
    {{>Surface template="headerFooter" class="timbre-main"
      modifier="StateModifier" translate=menuTranslate}}
    {{/ContainerSurface}}
    </template>

    <template name="headerFooter">
    {{#HeaderFooterLayout size="[undefined,undefined]" headerSize="70" footerSize="30"  }}
        {{#Surface target="header" }}
            {{> header}}
        {{/Surface}}

        {{#View target="content" size="[undefined,undefined]" }}
        {{>Scrollview id="scrollview" template="scrollview"  size="[undefined,undefined]" items=items paginated="true" direction="0" }}

        {{#Surface id="pageIndicator" class="red-bg" size="[undefined, 20]" }}
            {{> pageIndicator}}
        {{/Surface}}
        {{/View}}

        {{#Surface target="footer" class="smoke-bg footer"}}
            {{> footer}}
        {{/Surface}}
    {{/HeaderFooterLayout}}
</template>

but I get the error: " [famous-views]  You tried to embed a HeaderFooterLayout inside a Surface (parent: Famous.Surface, template: Template.home).  Surfaces are endpoints in the Famous Render Tree and may not contain children themselves.  See https://github.com/gadicc/meteor-famous-views/issues/78 for more info." 

There error message is clear. I can't do it that way. But I'm not sure what approach to take. Any ideas?

-Phil

**Comment by PEM--** [comment]
It all depends on the way you are calling your `screen` template. If it's immediate parent in your render tree is a `famousContext` you are basically encapsulating a context in a context. That would serve no purpose. On the other hand, if you have embedded your `screen` template into a larger app, the [ContainerSurface](http://famo.us/docs/surfaces/ContainerSurface) acts as an encapsulation mechanism allowing you to set different properties on the contexts.

Check this example: [fview-devices demo](http://fview-devices.meteor.com). In this plugin, each device owns a [ContainerSurface](http://famo.us/docs/surfaces/ContainerSurface) that encapsulates a simple app. The last example uses a perspective specifically to create a 3D out of the screen effect. This perspective is only required on this example. Thus, by applying it only on this specific last context, I avoid modifying the behavior of the main context (which could result in glitches on all the other examples).
