### ISSUE TITLE
Surface .rendered() fires before DOM fragment is attached to document

### ISSUE THREAD

**Issue by meteorjs3000** [gadicc/meteor-famous-views#192]
I'm using `mrt:garlic` to automatically persist form values after changing the route, which works when the form elements are not on a `Surface`. But when they are, the values are not persisting. Any idea how I can get them to work once more?

I have created [a repo here](https://github.com/meteorjs3000/famous-views-garlic-problem) to reproduce the problem.

**Comment by gadicc** [comment]
Pretty sure this is working now, and just added a test for it in https://github.com/gadicc/meteor-famous-views/commit/9795ba17604c188350dfa0d994a27f9ccb4a138e.  Feel free to reopen if you're still having issues.
