### ISSUE TITLE
*** DEC 2014 / JAN 2014 UPDATE ***

### ISSUE THREAD

**Issue by gadicc** [gadicc/meteor-famous-views#196]
*Yeah, GitHub isn't the best place for these... we'll do a blog next year, I promise :)*

So, due to some unexpected circumstances, I find myself going on a surprise holiday to Thailand :)  I'm a bit behind from trying to get organized for an unplanned trip, and unfortunately, this means I'll also be absent on GitHub until mid-January.

I hope you all noticed the truly fantastic contributions by @PEM-- over the last few months.  I had planned a different announcement, but I'd really like to express a big thank you here for his coding, inspiration, support and commitment to this the project, which is very appreciated :>  That and the fact that he has graciously agreed to make sure things don't grind to a complete halt during my absence, and despite his own busy schedule, will be minding the repro while I am on white sandy beaches :)

Although things have been winding down, we did squeeze through one more big update this year.  As always, keep track of [History.md](https://github.com/gadicc/meteor-famous-views/blob/master/History.md) to see what's been going on.  We have some big surprises planned for next year!  It's gonna be awesome :)

**Comment by swennemans** [comment]
Enjoy your holiday man! 

Finally I have a REAL project where I can use famous-views on. Will have a lot of catching up to do with all those updates. Looking forward to it!

**Comment by gadicc** [comment]
Thanks everyone for all your kind words!

It's been a slow start catching up on everything but I'm slowly getting back into the swing of things.  Four issues have been closed already, mentioned so far in [History.md](https://github.com/gadicc/meteor-famous-views/blob/master/History.md).  There should be a v0.1.31 release later this week.  The surprises I spoke about last year are about two weeks away :>

@PEM--, @mcbain, @kevohagan - many thanks :)  @splendido, I hope so!  This year looks like it has a lot of promise ahead, expecting good things :)

@Lauricio, Thailand was indeed awesome!  Had a superb time there.  Was tempted to move to Koh Phi Phi for a few months with my laptop and work from there, enjoying beach bar sunsets every night :>  Maybe one day when I retire :>

@swennemans, let me know how the project has been going, and if you need any help (besides the open issues we're already discussing).  What is the project, if you're allowed to share details?

**Comment by splendido** [comment]
Welcome back, we missed you!!!
