### ISSUE TITLE
getting started repo?

### ISSUE THREAD

**Issue by dcsan** [gadicc/meteor-famous-views#197]
It's been months since i touched famous, so I set up a small repo to test this with. 
I can use famono OK, but following the snippets on this projects home page
I just get:

```js

ContainerSurface.js:2 
Uncaught TypeError: Cannot read property 'ContainerSurface' of undefined
ContainerSurface.js:2 (anonymous function)famous-views.js:
27 FView.runReadiesfamous-views.js:111 (anonymous function)startup_client.js:63 Meteor.startupfamous-views.js:71 FView.startupfamous-views.js:139 (anonymous function)startup_client.js:30 runStartupCallbacksstartup_client.js:32 ready
```
repo:
https://github.com/dcsan/fbox/tree/master/app

is there an actual working skeleton app somewhere?

**Comment by gadicc** [comment]
Hey @dcsan, nice to see you back here :)  Sorry for the very late reply, I've been away travelling in the holidays with no internet and am slowly catching up on everything.

There's a "quickstart" repo at https://github.com/gadicc/fview-quickstart mentioned on the Quick Start page.  There's also a slightly neglected WIP at https://github.com/gadicc/fview-demo.  The basic quick start and iron-router quick start are also both linked to MeteorPad too, and we have have another surprise in the Quick Start planned for the next few weeks.

I'm also happy to take a look at your code after I've gotten through more issues, so please keep us posted.

**Comment by gadicc** [comment]
Hey, sorry, I know I replied late, but I'm closing this just to try make order of all the old issues.  Feel free to reopen if you're still having issues.  Also, I couldn't access the repo.
