### ISSUE TITLE
Swiping between full screen Surfaces

### ISSUE THREAD

**Issue by ccorcos** [gadicc/meteor-famous-views#198]
How can I pull this off

http://stackoverflow.com/questions/23649958/how-to-swipe-between-surfaces-in-famo-us

I'm having trouble translating from Famous javascript to Blaze.

**Comment by gadicc** [comment]
You can also set paginated to true and not specify a size for the surfaces, to use the full size.  To modify PEM--'s example, it would look like this:

```jade
+Scrollview direction="X" paginated="true" size="[undefined,undefined]"
  +famousEach surfaces
    +Surface
      | Surface #{_id}
```

You can see a working example at http://fview-demo.meteor.com/ (still a WIP) with the source code https://github.com/gadicc/fview-demo/blob/master/client/fview-demo.jade.

**Comment by ccorcos** [comment]
That looks great! Although, I'm noticing that most browsers use a scroll to the side to go forwards and backward which is kind of annoying...
