### ISSUE TITLE
[famousEach] support order-changes

### ISSUE THREAD

**Issue by mcbain** [gadicc/meteor-famous-views#201]
Currently most of the core famous layouts do not reflow when items in the viewsequence just change the order. IMHO core famous layouts cannot detect this, because there is no '_id' to identify the items, just the length of the sequence. 
Since the meteors 'each' actually can detect such changes we need a solution to trigger a reflow  - e.g. invoke a `triggerReflow` method registered with the view.    
 
      FView.registerView('XYZView', XYZView, {
          ....,
          triggerReflow : function() {
                this.view.setDirty(true);
          }
      }

see also https://github.com/IjzerenHein/famous-flex/issues/39

**Comment by gadicc** [comment]
Hey, sorry for the long delay... I've been away without internet for the holidays.  Haven't forgotten about the stuff from last year either, will get there eventually :>  Thanks for the patience!

I'd prefer to simply allow overrides on any of the famousEach observe events, and then leave it to the dev to decide what to do on each event.  I'll try do docs (and tests) tomorrow, but in the meantime take a look at the diff below.

The format is the same as Meteor's `observe()`, with two extra args, `_super` and `eachView`.  `this` will be the view's `fview`.  `_super()` will run the normal behaviour (which by default no longer runs if an overrride is present), and `eachView` contains everything needed to totally change the behaviour, including e.g. `eachView.fview.children`, etc.

So you could do:

```js
  FView.registerView('XYZView', XYZView, {
      movedTo: function(id, doc, fromIndex, toIndex, _super, eachView) {
            _super();
            this.view.setDirty(true);
      }
  }
```

I was thinking to also maybe just always run the `_super()` code by default unless the override function returns `false`... but probably for overrides people will "usually" either not want that code to be run or might want it run in a different order.  Your thoughts are welcome.

**Comment by gadicc** [comment]
You can play around with it in `v0.1.31-pre.2`.

**Comment by gadicc** [comment]
Closing since I'm trying to make headway through all these issues :>  Please reopen if it doesn't work as necessary.
