### ISSUE TITLE
fview-animate #famousIf destroyPrevented error blocking the leave-animation

### ISSUE THREAD

**Issue by swennemans** [gadicc/meteor-famous-views#204]
I tried to get the awesome fview-animate plugin to work with #famousIf. The enter animation works fine, the leave animation doesn't work. In the console it logs 'destroyPrevented', what probably causes the leave animation not to fire. 

I've made a very simple project to show the problem: https://github.com/swennemans/fview-animate-famousIf , to clarify the problem. 

Am I doing something wrong, or is something broken?

btw: I posted this issue (without the example code) on fview-animate. It's way more active here. Hopefully you don't mind I'm crossposting. 

Sven

**Comment by gadicc** [comment]
Hey, I cloned the repo, but I'm not entirely sure what you're expecting and what you're seeing instead.  When I click "CLICK", it transitions between Template 1 and Template 2.  In the console, I do see the final destroy:

> clicked
console.coffee:18  debug:  [famous-views]  famousIf (#2) is now true (parent: Famous.View, template: Template.example)
**console.coffee:18  debug:  [famous-views]  Destroying Animate (#12) and children (destroyPrevented)**
console.coffee:18  debug:  [famous-views]  New Animate (#14), content from inline block (parent: Template.template1)
console.coffee:18  debug:  [famous-views]  New Surface (#15), content from inline block (parent: Famous.Animate, template: Template.template1)
**console.coffee:18  debug:  [famous-views]  Destroying Animate (#12) and children**
console.coffee:18  debug:  [famous-views]  Destroying Surface (#13) and children

Also, I couldn't find your issue on fview-animate repo, can you put a link to it here so the issues will be connected?

P.S. for animating entire template add/removes, I'd recommend rather using a RenderController?

**Comment by swennemans** [comment]
He gadicc thanks for taking the time to look into it. I hope you had an awesome holiday. 

Maybe I'm interpreting the functionality of this plugin wrong. Maybe I can explain my though better with another animation:

```javascript
  enter : function() {
        return function(stateModifier, done) {
            stateModifier.setTransform(Transform.translate(100, 0, 0), {
                duration: 300,
                curve: Easing.outBack}, done);
        };


    },

    leave : function() {
        return function(stateModifier, done) {
            stateModifier.setTransform(Transform.translate(200, 0, 0), {
                duration: 300,
                curve: Easing.outBack}, done);
        };
    }
```
What I expected is: 
- On enter the modifier will slide the surface to x-coordinate 100 (this is working perfectly); 
- On leave the modifier will slide the surface to x-coordinate 300 and will be destroyed (this doesn't work). 

If I'm misunderstanding the functionality then please let me know. I'm aware of the renderController I use it in a different setting and it works very good :)

In this specific use case I would like to slide-in a menu from off-screen to on-screen. I've created this functionality by placing a surface outside of viewport and slide it in and slide it outside the viewport again when closing. This works, but I though the fview-animate plugin would be a cleaner solution.

Regarding the issue on the fview-repo I closed it because I asked the question here. It's at: https://github.com/mj-networks/famous-animate/issues/3  I can reopen the issue if you'd like. 

Thanks!

Sven

**Comment by gadicc** [comment]
Ah ok, we're on the same page now :)  Never thought about using #Animate like that before, nice original thought process.

Your current way of doing it is a bit more efficient though... since opening/closing the menuu is probably quite a common procedure, it's better to not have the overhead of creating/destroying the template every time.  Are you doing it like in the Timbre menu demo with a reactive `menuTranslate` helper?

Unfortunately I'm not a famous-animate expert... maybe @mcbain can chime in.  I will mention that we have an outstanding issue with destroys (https://github.com/gadicc/meteor-famous-views/issues/153)... that's on my list for this week, so we can also see if that makes any difference.

**Comment by gadicc** [comment]
And thanks yeah holiday was amazing, thank you!

**Comment by gadicc** [comment]
I also have another idea, can you try registering the function by name with `FView.registerTransition` (as per fview-animate docs), and see if it works when calling it by the registered string name?  Just noticed another possible cause for this; @mcbain, see https://github.com/mj-networks/famous-animate/blob/9686548a59796c25768ca68b331c2380d279b3a6/src/AnimateView.js#L77, should be `onLeave`, no?

**Comment by swennemans** [comment]
Thanks for your tip regarding what is more efficient. Yes I used the Timbre menu as an example. 

I've just tried to register the function by name with FView.registerTransition but the the effect is the same as with enter / leave functions.

**Comment by gadicc** [comment]
Sorry, I noticed now that due to another issue in the code you need to use strings for both functions, even though you're just trying to change the 2nd one.  I'll submit a PR to fview-animate to get this fixed up.  In the meantime, I've tested that the following works:

```js
FView.registerTransition('enter', function(stateModifier, done) {
    stateModifier.setOpacity(0);
    stateModifier.setOpacity(1, { duration: 500, curve: 'easeOut' }, done);
});
FView.registerTransition('leave', function(stateModifier, done) {
    stateModifier.setOpacity(0, { duration: 500, curve: 'easeOut' }, done);
});
```

In Template1 and Template2:

```handlebars
    {{#Animate size='[200,200]' onEnter="enter" onLeave="leave"}}
```

**Comment by gadicc** [comment]
Closing just because it's not a famous-views issue, let's track this in the PR here:
https://github.com/mj-networks/famous-animate/pull/4

**Comment by swennemans** [comment]
Yes the above code works :)
