### ISSUE TITLE
Newest Build has error on build

### ISSUE THREAD

**Issue by kcrao** [gadicc/meteor-famous-views#205]
When we downloaded the latest repository from GIt, we ran into an issue.
When we build the project we receive an error, "unknown package: gadicohen:fview-scrollbars"

**Comment by gadicc** [comment]
Hey, I've fixed this.  Just note it's always better to use an actual release rather than the latest master, which can include pre-releases and is less likely to be considered "stable".  Is there a reason you're not using the package via the Meteor Package Server / Atmosphere?

**Comment by gadicc** [comment]
Closing since I'm trying to make headway through all these issues :>  Please reopen if you're still having issues.
