### ISSUE TITLE
meteor listen for famous events

### ISSUE THREAD

**Issue by ivan9074** [gadicc/meteor-famous-views#209]
Hi i have tried you package and it was really cool but i wanted to keep the frameworks separate. So i thought i would made them interact via Events

Since, you have build this package which encapsulates them. Maybe you could give me a hand with this

i am doing the following chain of events.

the surfaces emits a **flipped** event

**this.front.on('mouseover', function() {
            this.flipperView.flip({ duration : 750, curve: Famous.Easing.outBounce   });
            this._eventOutput.emit('flipped');**

this is capture by it's view container

**cell.on('flipped', function() {
                debugger;
                this.trigger('flippedOut') // this is the one a in having trouble
            });**

which triggers/emits/broadcast **i am a bit confused here**

and finally the event **flippedOut** should be capture inside an Event in meteor.

i have tried these two approachs
1)
**Template.app.events({
	'flippedOut' : function() {
		debugger;
	}
})**

2
this is indise the 

**Template.app.rendered = function() {
..
Famous.Engine.on('flippedOut', function() {
		debugger;
	});
...
}**

But i cant manage to get to the Meteor side.

**Comment by gadicc** [comment]
Hey, it's a bit hard to debug this without seeing the full code.  But assuming the `flippedOut` event is coming from a view that's wrapped with famous-views (#Flipper I guess), and is added via inclusion, it should work by using `Template.flipper.famousEvents({ ... })`.  Make sure you've thoroughly read http://famous-views.meteor.com/examples/events.

Beyond what's in that page, it's important to remember there's no concept of events "bubbling up" (propagating) like in the DOM.  So you can't listen for the event in famous.Engine or in an ancestor template, unless you've used the appropriate famous `subscribe` / `pipe` statements to connect them all.
