### ISSUE TITLE
Can we register custom surfaces?

### ISSUE THREAD

**Issue by maximusmortis** [gadicc/meteor-famous-views#212]
I'd like to extend the surface class to implement material design ripple effect:

```javascript
// Extend surface to tap into .render()
function RippleSurface (options) {
  Surface.apply(this, arguments);
  // ...
  this.on("mousedown", this.ripple);
  this.on("deploy", this.postDeploy);
}

RippleSurface.prototype.render = function () {
  // ...
  return this.id;
}
```

and then:
```
{{> RippleSurface options... }}
```

Thanks!

**Comment by gadicc** [comment]
Yup, 

```js
FView.registerView("RippleSurface", RippleSurface);
```

:-)   see http://famous-views.meteor.com/views/README


On 06 February 2015 6:49:50 PM SAST, Maximus Mortis II <notifications@github.com> wrote:
>I'd like to extend the surface class to implement material design
>ripple effect:
>
>```javascript
>// Extend surface to tap into .render()
>function RippleSurface (options) {
>  Surface.apply(this, arguments);
>  // ...
>  this.on("mousedown", this.ripple);
>  this.on("deploy", this.postDeploy);
>}
>
>RippleSurface.prototype.render = function () {
>  // ...
>  return this.id;
>}
>```
>
>and then:
>```
>{{> RippleSurface options... }}
>```
>
>Thanks!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/gadicc/meteor-famous-views/issues/212

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by maximusmortis** [comment]
Thanks for the answer.

I ended up overriding the surface.render method in meteor's rendered callback.
Anyway, thanks for your hard work and awesome library :)

**Comment by gadicc** [comment]
Sure :)
