### ISSUE TITLE
Upcoming talks & meetups

### ISSUE THREAD

**Issue by gadicc** [gadicc/meteor-famous-views#213]
Want to learn more about famous-views up close and personal?  Join us at one of the meetups below.  Even better, are you already using famous-views and feel comfortable talking about it?  I end up doing a lot of these talks myself, which gets especially difficult with timezone differences... so any help appreciated :)

### 2015

**June**

* Thu June 25th, @ [Meteor London](http://www.meetup.com/Meteor-London/), England with @gadicc

### 2015

**April**

* Thu Apr 9th, 7pm EDT joint [Ottawa Famo.us](http://www.meetup.com/Ottawa-Famous/events/218821486/) and [Ottawa Meteor](http://www.meetup.com/Meteor-Ottawa/events/221461275/) meetup, Canada with @gadicc, live-streaming; [slides](http://meetup-fview-ottawa.meteor.com/), [video](https://www.youtube.com/watch?v=9lW3kOy2mAQ).

**February**

* Wed 18th Feb @ [Meteor Cape Town](http://www.meetup.com/Meteor-Cape-Town/events/220408071/), South Africa with @gadicc ([slides](https://github.com/gadicc/meetup-fview-ct))

**Comment by splendido** [comment]
There's a very nice video [here](https://www.youtube.com/watch?v=3FlndpRiEsY#t=139) taken form the January London DevShop

**Comment by gadicc** [comment]
Thanks @splendido, great to see the project spreading around the globe :)  I'm actually going to be in London later this year and could potentially give a full length talk about the project.

**Comment by splendido** [comment]
It would be fantastic to see you at a Londo DevShop!
...I most likely won't be there, but since they usually publish video might be a good chance to see you *live* ;-)

**Comment by ambujpunn** [comment]
@gadicc is it possible to have a live stream of it so the rest of us from other parts of the world could also "attend"? Great work btw :)

**Comment by gadicc** [comment]
thanks guys :)

the video from the ottawa meetup is at https://www.youtube.com/watch?v=9lW3kOy2mAQ.  disclaimer: it was 2am for me.

the london meetups as far as i know are usually streamed line, so see you all next month!

**Comment by gadicc** [comment]
hey all, thanks, moving this to http://forums.famous-views.org/t/upcoming-talks-and-meetups/15.
