### ISSUE TITLE
Size Constraint

### ISSUE THREAD

**Issue by robmoggach** [gadicc/meteor-famous-views#217]
I would love to have something like https://github.com/IjzerenHein/famous-sizeconstraint added to Modifiers,ContainerSurfaces,Surfaces etc.

Tag this as a feature request please!

Specifically I'm trying to create a fluid layout with 3D surfaces that have minimum widths/ratios and scale fluidly to different device/browser window sizes.

**Comment by gadicc** [comment]
Seems like a good idea...
https://atmospherejs.com/gadicohen/fview-sizeconstraint :)

Notes:

1. Seems to be a bug in ordering that I'm looking into, when changing routes
1. scaleX,Y,Z is broken in famous-views < 0.1.33

Let me know what you come up with.  Also see https://fview-lab.meteor.com/fview-team in case that's anything like what you're trying to do, it's a FlexScrollView CollectionLayout with custom itemSize function to support min-max sizing of items.

**Comment by robmoggach** [comment]
amazing - will start playing with it -
