### ISSUE TITLE
Overlaying Surfaces

### ISSUE THREAD

**Issue by nickmacia** [gadicc/meteor-famous-views#218]
Hey, Im new to the famous/meteor stack and have transitioned into using this library over pure famous/meteor due to the routing capabilities that this offers. But I'm having some issues overlaying surfaces on top of each other, such as in the centering or proportional sizing examples here (http://famous-views.meteor.com/examples/layouts). What happens instead is that I get one surface under the other, as if I rendered two divs after each other. 

Here's the template which calls the code in question: 

    <template name='someTemplate'>
      {{#Modifier}}
         {{#Surface size='[undefined, 568]' properties='color: white;' class='bg'}}
         {{/Surface}}
         {{#Surface}}
           <h1> hey </h1>
         {{/Surface}}
       {{/Modifier}}
     </template>
And here are the contents of the layout template which redirects to it. 

      {{#famousContext id='mainCtx'}}
        {{#RenderController}}
           {{>yield}}
       {{/RenderController}}
     {{/famousContext}}

This is super natural and easy to do in pure famous, but I'm getting some push back here. I sense that I must be making an obvious mistake, but I am not sure where.

Addendum: 
I tried using the same origin and align properties used in the example in the docs, to no avail. Also, when I just copy and paste the proportional sizing example into my someTemplate, I get the same effect, so it must be something with the interaction between famousContext or RenderController.

**Comment by pmwisdom** [comment]
I'm having the same exact problem. 

I have a header footer layout, with a render controller as my content target, and I render two surfaces inside the template thats yielding and which ever surface is rendered last overlays the other completely.

**Comment by PEM--** [comment]
Hi guys, Welcome in famous-views.

Enforcing drawing order like this may end up with weird results when reactive calculation are done over famous's virtual DOM. Your second `Surface` may end up hidden by your background `Surface`. I prefer declaring my intent over betting on what these engines would do. Therefore, I manually set my `translate`.

Here's a little example that should lead you on the right track. This example uses CS, Jade and CSSC for brevity.
```bash
meteor create fview-sample
cd fview-sample
rm -rf *
mkdir client
meteor add coffeescript gadicohen:famous-views iron:router mjn:famous mquandalle:jade pierreeric:cssc pierreeric:cssc-colors pierreeric:cssc-famous pierreeric:cssc-normalize
```

**client/main.jade**
```jade
head
  title Sample
  meta(charset='utf-8')
  meta(name='viewport', content='width=device-width, maximum-scale=1, initial-scale=1, user-scalable=no')
  meta(name='apple-mobile-web-app-capable', content='yes')
  meta(name='apple-mobile-web-app-status-bar-style', content='black')
  meta(name='apple-mobile-web-app-capable', content='yes')
  meta(name='mobile-web-app-capable', content='yes')

template(name='layout')
  +famousContext id='mainCtx'
    +RenderController
      +yield

template(name='bgred')
  +Modifier
    +Surface size='[undefined, 568]' translate='[0,0,0]' class='bgred'
      | 
    +Surface translate='[0,0,1]'
      h1 Red page
      p: a(href='/bggreen') Go green
    
template(name='bggreen')
  +Modifier
    +Surface size='[undefined, 568]' translate='[0,0,0]' class='bggreen'
      | 
    +Surface translate='[0,0,1]'
      h1 Green page
      p: a(href='/') Go red
```

**client/main.coffee**
```coffee
Router.configure layoutTemplate: 'layout'
Router.route '/', -> @render 'bgred'
Router.route '/bggreen'

Template.layout.created = ->
  css = new CSSC
  textColor = CSSC.yellow
  css.add 'h1', color: textColor
  css.add 'a', color: textColor
  css.add '.bgred', backgroundColor: CSSC.red
  css.add '.bggreen', backgroundColor: CSSC.green
```
