### ISSUE TITLE
Unable to use RenderController

### ISSUE THREAD

**Issue by jaredtmartin** [gadicc/meteor-famous-views#219]
I'm trying to use RenderController similar to this example.
http://famous-views.meteor.com/views/RenderController

See my simple example here:
http://meteorpad.com/pad/aXCCim977wyy6DgSE/Copy%20of%20famous-views%20basic
Why doesn't the welcome message appear?

**Comment by feidens** [comment]
Perhaps this helps
http://meteorpad.com/pad/EZhukJvcejousxhqZ/Copy%20of%20famous-views%20basic%20-%201

**Comment by jaredtmartin** [comment]
I'm trying not to use Iron Router.  I don't use it in my projects cause it seems a little to big.

**Comment by gadicc** [comment]
@jaredtmartin, just wrap the contents of your welcome template in `{{#Surface}} ... {{/Surface}}`, and then it will display properly.  In Famo.us, anything that is displayed has to be in a Surface, it's the only place where HTML/text can go and the only part of the famo.us render tree that will ever get put on a DOM.

@feldens, thanks so much for helping out!  I really struggle sometimes to maintain such a big open source project in my spare time and it's a great help when other users get involved in helping their peers.  kudos :)

**Comment by jaredtmartin** [comment]
That was it.  Thanks.
