### ISSUE TITLE
famousEach renders diagonally instead of horizontally 

### ISSUE THREAD

**Issue by nickmacia** [gadicc/meteor-famous-views#222]
I'm calling famousEach on a loop and its rendering it on a diagonal axis as opposed to a horizontal one. I've played around with the origin and align settings and it just moves around the diagonal as opposed to moving each individual surface to correct the positioning. This doesn't happen on my other loop and its nearly the same layout. 

    <template name='myTemplate>
       {{#HeaderFooterLayout size='[undefined, 568]' headerSize=0 footerSize=100 translate='[0, 0, 0]'}}
          {{#Surface target='header'}}
          {{/Surface}}

      {{#Surface target='content' size='[undefined, 200]'}}
        <p> content </p>
      {{/Surface}}
  
      {{#Scrollview target='footer' size='[undefined, 200]' direction='X' translate='[0, 0, 0]'     properties='backgroundColor: red;'}}

    {{#Surface size='[100, 100]' translate='[0, 0, 0]' }}
      {{> upload}}
    {{/Surface}}

    {{#famousEach myLoopData}}
      {{#Surface  size='[100, 100]' translate='[0, 0, 0]' origin='[0, 0]' align='[0, 0]'}}
      <img src="{{ myUrl }}" style='height:100px;width:100px;'>
      {{/Surface}}
    {{/famousEach}}

     {{/Scrollview}}

    {{/HeaderFooterLayout}}
    </template>

**Comment by gadicc** [comment]
Diagonally?  Just to double check, if you're using raix:famono did you include the css from their README / the bottom of our quickstart? 

On 06 March 2015 12:37:04 AM SAST, Nick <notifications@github.com> wrote:
>I'm calling famousEach on a loop and its rendering it on a diagonal
>axis as opposed to a horizontal one. I've played around with the origin
>and align settings and it just moves around the diagonal as opposed to
>moving each individual surface to correct the positioning. This doesn't
>happen on my other loop and its nearly the same layout. 
>    <template name='myTemplate'>
>{{#HeaderFooterLayout size='[undefined, 568]' headerSize=0
>footerSize=100 translate='[0, 0, 0]'}}
>      {{#Surface target='header'}}
>      {{/Surface}}
>
>      {{#Surface target='content' size='[undefined, 200]'}}
>        <p> content </p>
>      {{/Surface}}
>  
>{{#Scrollview target='footer' size='[undefined, 200]' direction='X'
>translate='[0, 0, 0]'     properties='backgroundColor: red;'}}
>
>    {{#Surface size='[100, 100]' translate='[0, 0, 0]' }}
>      {{> upload}}
>    {{/Surface}}
>
>    {{#famousEach myLoopData}}
>{{#Surface  size='[100, 100]' translate='[0, 0, 0]' origin='[0, 0]'
>align='[0, 0]'}}
>      <img src="{{ myUrl }}" style='height:100px;width:100px;'>
>      {{/Surface}}
>    {{/famousEach}}
>
>     {{/Scrollview}}
>
>
>
>    {{/HeaderFooterLayout}}
></template>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/gadicc/meteor-famous-views/issues/222

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nickmacia** [comment]
That was it! Thanks for the help.
