### ISSUE TITLE
FlexLayoutController  TabView Layout

### ISSUE THREAD

**Issue by ganySA** [gadicc/meteor-famous-views#234]
Hi

does anyone have a working example of a simple tabview layout? I cannot seem to get this working at all.

Thanks

**Comment by gadicc** [comment]
@ShawnOceanHu, were you maybe working on this with fview-flex?

**Comment by ShawnOceanHu** [comment]
Hi @gadicc, nope I haven't tested/used TabBar though I think it should at least work from JS. I'm currently doing an Android project for my employer and a project of my own so I haven't really got time to do famo.us framework level devs.

Hi @ganySA , have you tried creating the TabBar in JS ?

**Comment by gadicc** [comment]
@ShawnOceanHu, cool, thanks for the report back :>

**Comment by gadicc** [comment]
I'm going to close this now since there's a working implement in fview-flex, with docs on the way.  There's example code at https://github.com/gadicc/fview-flex/tree/master/demo, there'll be documentation on the live site soon.  http://fview-flex.meteor.com/TabBar
