### ISSUE TITLE
Question: using require

### ISSUE THREAD

**Issue by ganySA** [gadicc/meteor-famous-views#235]
Hi

I see the documentation states using "require" to load additional layouts as the below:

    FView.registerView('View', require("famous/core/View") [,options]);

When i attempt this i get a "require" is not defined. What module loader should i be installing?

The documentation on the website states something slightly different:

FView.registerView('Scrollview', famous.views.Scrollview);

**Comment by gadicc** [comment]
Yeah, website documentation is more up-to-date / correct... I should update the README.  Both mjn:famous and raix:famono work with straight globals (famono only bundles what you use in your code though).
