### ISSUE TITLE
Fileinput opens Filepicker two times on cordova

### ISSUE THREAD

**Issue by GeorgS** [gadicc/meteor-famous-views#241]
Here is an example to reproduce the issue. Use the chrome DevTools Device Emulator to emulate touch events. When the file input is clicked it triggers the File-picker two times. This happens for me on android with cordova and inside the Device Emulator with touch event emulation enabled.

https://github.com/GeorgS/famous-views-241

**Comment by gadicc** [comment]
Could be the fastclick issue?  https://github.com/gadicc/meteor-famous-views/issues/89

**Comment by gadicc** [comment]
Feel free to re-open if this wasn't issue #89 and you still don't have it working.

**Comment by GeorgS** [comment]
This is probably the issue, I will test it.
I currently use a workaround where I hide the file input and listen for a click on a button which then triggers a click event on the input.
