### ISSUE TITLE
Gitter chat please

### ISSUE THREAD

**Issue by timfam** [gadicc/meteor-famous-views#242]
It will be great to have a dedicated chat room on gitter for this project. It will help out the community a lot. Please think about

**Comment by timfam** [comment]
@PEM-- could you setup the gitter room and include it in th readMe it is dead simple to do

**Comment by PEM--** [comment]
If you ensure the community management for it, I'm doing it right way. Good enough?

**Comment by timfam** [comment]
Yes, I am more than happy to do that, In fact super happy to do that!

**Comment by PEM--** [comment]
Let's ride on!

**Comment by gadicc** [comment]
thanks @timfam and @PEM-- , you guys rock :)
