### ISSUE TITLE
Tutorial: For those who are new!

### ISSUE THREAD

**Issue by ganySA** [gadicc/meteor-famous-views#251]
This is a great tutorial i just found - might be good to put in as a read me?

http://www.tutas-labs.com/famous-meteor-integration-part-4/

There are many but that is where the famous starts.

**Comment by gadicc** [comment]
Where did you find it?  It's mentioned on the [Support Page](http://famous-views.meteor.com/support), the [Quick Start](http://famous-views.meteor.com/start) and [Layouts](http://famous-views.meteor.com/examples/layouts) pages.  Since yesterday :)

**Comment by ganySA** [comment]
google:)

**Comment by ShawnOceanHu** [comment]
https://famous-views.meteor.com/ is a great to learn meteor-famous-views @ganySA

**Comment by gadicc** [comment]
i'm going to close this since it's on the website now and not really an ongoing discussion.
