### ISSUE TITLE
Question: programmatically create famous surface

### ISSUE THREAD

**Issue by ganySA** [gadicc/meteor-famous-views#252]
Hi

Is there a way to emulate {{#Surface}}{{/Surface}} using code and still get all the famous meteor goodness?

Im looking at something like:
    var x = new famous.core.Surface({template: Template.x});

Thanks

**Comment by PEM--** [comment]
Hi @ganySA. For Q/A, we have created a Gitter accounts. That's avoid confusing questions with issues. Check this out: https://gitter.im/gadicc/meteor-famous-views
