### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by trusktr** [gadicc/meteor-famous-views#259]
Caused by the following simple template: 

```jade
head
    title

body
    div(class='scene')
        +Node(id="rootNode")
```

There's no JavaScript at all.

**Comment by trusktr** [comment]
Oh doh! Forgot the scene. I was thinking in Framework for a second, where you don't need to declare the scene.

**Comment by gadicc** [comment]
Yeah, not going to let you live this one down :)

**Comment by trusktr** [comment]
Hhahahahaaaaaa :laughing:
