### ISSUE TITLE
Change DOMElement to DomElement

### ISSUE THREAD

**Issue by genyded** [gadicc/meteor-famous-views#265]
This may seem trivial, but DOMElement looks out of place in the rest of the code (also makes it read like "dome" something) and is in consistent with the pure camel case naming for EVERYTHING else.

**Comment by PEM--** [comment]
This sticks to API's conventions brought by W3C in 1998 and applied to Famo.us's API: http://famous.org/docs/dom-renderables/DOMElement.html.

Though, I really share your point of view and in my humble opinion the W3C should also have applied a bit more consistency on its DOM API (DOMString, DOMException, ... :grimacing: ), deriving from it would loose users.
