### ISSUE TITLE
How can I add a event in-side Content of iframe.

### ISSUE THREAD

**Issue by PankajJatav** [gadicc/meteor-famous-views#266]
Hey I just Created a node like this
<iframe src="" style="height:500px ; width:500px ">
{{#Scene id="screen"}}
    	{{#Node id = "node" size = "100%,100%" align="[0.5,0.5]"  mountPoint = "[0.5,0.5]"}}
                //My node that can move 
         {{/Node}} 
{{/Scene}}     
</iframe>

//Then I add a button
<button id="button">Click</button>

Now i want to move the nodes which are inside of Node(id = 'noode')

I know you you want to  say that don't use iframe.
But my problem is i am creating some kind of roller.
I am moving the nodes using setAlign by adding duration, that give me some real time feels.
So setting their Align some of node will go outside that i want to see.
So Any Idea how can i solve this or How can I add a event for iframe

**Comment by gadicc** [comment]
Hey, unfortunately the new Famous engine has been a bit of a disappointment.  See the update at http://forums.famous-views.org/t/with-much-regret-the-final-update/102/.  It's not quite as bleak as it sounds though, you'll see a few posts down that some really awesome stuff is happening in the community (that I'm involved in), but if this project continues it won't be with the official Famous library, and the project is on hiatus for now.  Watch that thread for updates.  I've updated the README to reflect this too.

Back to your question :)  On the containing DOMElement, simply set `style="overflow: hidden"` (there are some z-index ordering issues with this on some browsers though).  You might also need to add a new DOMElement for this, Famous will embed it for you.  e.g.:

``` jade
+Scene
  +Node
    // Note these next two are on the same level
    +DOMElement style="overflow: hidden"
    +Node
      +DOMElement // will be contained inside the parent Node's DOMElement
    +Node
      +DOMElement // will be contained inside the parent Node's DOMElement
```

Does that make sense?

Also, we're trying to put questions (vs bug reports / feature requests) on http://forums.famous-views.org/, but as you realized things might be quiet there for a bit.

**Comment by PankajJatav** [comment]
Thanks for Replay. But i solve this problem already using rotation.
I just rotate the nodes to 90' degree which go outside.
Middle to 0 degree.
Side node to 45 degree. That give me a feel of real slot machine.

@gadicc Thanks for design awesome famous view. nice work.

**Comment by gadicc** [comment]
Thanks, @PankajJatav!  Send us a link if it's not a private project, always great seeing user code.

**Comment by PankajJatav** [comment]
@gadicc It's client project.
But i am working on some public new example(game or animation) once they complete i will share it.

**Comment by gadicc** [comment]
That's awesome!  Thanks :)
