### ISSUE TITLE
Support multiple {{#Context}} Views

### ISSUE THREAD

**Issue by gadicc** [gadicc/meteor-famous-views#74]
Currently famous-views only supports working with a single, "main" context.

It's not currently a high priority, but I have been thinking of adding a {{#Context}} View.  This would actually let you create smaller Famo.us components that work in an existing site as opposed to needing to convert your whole app.  The downside (and why Famo.us doesn't mention this possibility too much either) is that you still need to be acutely aware of what the non-Famous parts of your app are doing (with CSS and JS) to be sure it doesn't affect performance.  So I've left this out for now but leaving the issue open in case people want to express their support for it.

Note, if you just need an additional context in an all-Famous app, `{{#ContainerSurface}}` actually creates a new context.  You can access it with `FView.byId('someContainer').view.context`.  When is this useful?  The best thing that comes to mind is when you want two views to have different perspectives.  (I should probably use this with the Flipper demo to prevent the menu bar disappearing on click).

**Comment by feeloo007** [comment]
Hello,

Is supported multiple context using raix:famono ?

It seems to be ok using mjn:famous but not using raix:famono.

Thank you for your help

Philippe

**Comment by gadicc** [comment]
Both are supported.  That sounds weird, because famous-views does the context stuff, and just relies on either of those to provide famo.us.  Can you show some sample code?  Are both mjn:famous and raix:famono giving you the same version of famo.us?

**Comment by feeloo007** [comment]
I wanted make an example on meteorpad but raix:famono loading failed. Everything is unknow.

How to détemine famo.us version ?

**Comment by feeloo007** [comment]
Sorry, I made a clean meteor app and now, is ok.

I don't know why but my older app doesn't do 'Ensure dependencies, Famono: downloading...'.

It seems to be ok now.

Thank you for your help.

Philippe

**Comment by gadicc** [comment]
I think it only does that once, or when changing versions.  Great news that you're up, if you see the error again let us know exactly what it says :>
